### ISSUE TITLE
Hooking in code

### ISSUE THREAD

**Issue by Life45** [HyperDbg/HyperDbg#112]
Hello, first of all this is a question. As asked before in https://github.com/HyperDbg/HyperDbg/issues/28 , my goal is to create an ept hook for a system function in code(not via commands in the controller) and activate the hook via an IOCTL command. The problem is that if i call the EptHook2 function directly giving my hook handler address rather than AsmGeneralDetourHook, hook handler will be called just fine but it will create an access violation on return, which i assume because there are additional restoring steps to do for returning to caller. I am aware that hyperdbg's main goal is not supporting this, but it would be good to still have the option. I would be glad if you can point me in the right direction.

To give you an example of what i need for additional clarification, it's present in [gbhv](https://github.com/Gbps/gbhv/blob/master/gbhv/ept.c#L562).

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating the issue.

What kind of hook do you want? I mean is it a hidden breakpoint hook or a detours-style hook?

**Comment by Life45** [comment]
It is a detours-style hook. For example let's say i want to hook NtWriteFile to return STATUS_INVALID_PARAMETER from my hook for a special file.

**Comment by SinaKarvandi** [comment]
In HyperDbg, detours-hook, as well as all the events, are configured from IOCTL here :
https://github.com/HyperDbg/HyperDbg/blob/112e5ab4b206bec1ca0ff67dd92bd495f8dde373/hyperdbg/hprdbghv/code/debugger/core/Debugger.c#L2198

and when they are triggered are handled by DebuggerTriggerEvent, in this case here:
https://github.com/HyperDbg/HyperDbg/blob/3b83d8563b4dbd142fa8c1d6a9eb0c2d55bea133/hyperdbg/hprdbghv/code/debugger/core/DebuggerEvents.c#L91

So, you need to modify these lines and put your code—no need for extra things to do.

Also, these hooks have some limitations, as described here:
https://docs.hyperdbg.org/commands/extension-commands/epthook2#remarks

Generally, it's preferred to use EPT Hidden breakpoints instead of these hooks.
And also, I'm just curious, why don't you use the script engine of the command for this purpose? It's super easy with the script engine. Is there any particular reason you don't use the script engine?

**Comment by Life45** [comment]
There isn't really a particular reason i don't use the script engine really, thanks for the response.

**Comment by SinaKarvandi** [comment]
By the way, please also consider using the script engine. We put hundreds of his hours into it to make these things easy.
Please take a look at some examples of the script engine. Maybe it convinced you to use it ;)

https://docs.hyperdbg.org/commands/scripting-language/examples
