### ISSUE TITLE
8K Byte allocation for the VMCS region

### ISSUE THREAD

**Issue by krispybyte** [HyperDbg/HyperDbg#150]
I've started researching about hypervisors (for intel's virtualization technology) a few days ago, your project seems like a great reference to read off, but I've noticed that there is an 8k byte allocation for the VMCS region (despite the comment saying it's 4), according to the intel manual (chapter C3, 24.2, "Format of the VMCS region")
"A VMCS region comprises up to 4-KBytes"
and you are allocating this size:
VmcsSize = 2 * VMCS_SIZE; (8k bytes)

anyways my question is if there's any reasoning for this or is this a mistake? keep in mind I'm new so I may have just overlooked something in intel's manual.

Thanks!

**Comment by SinaKarvandi** [comment]
Hi,

Thanks a lot for creating this issue.

We want to make sure to get a contiguous, aligned 4 KB. That's why we multiply it by 2.

Look at this line that sets the alignments.
https://github.com/HyperDbg/HyperDbg/blob/85f39b6baef0783f2dd6c74ff7b15199e0dc3679/hyperdbg/hprdbghv/code/vmm/vmx/VmxRegions.c#L131

However, as long as I know, if you request 4096 bytes from functions like ExAllocatePoolWithTag, then it returns an aligned address. But as we want to port HyperDbg to other OSes in the future, we didn't rely on this fact on Windows as it might not be accurate on different platforms.

**Comment by krispybyte** [comment]
Hey, I really appreciate the answer and I understand it now.
Thanks again!
