### ISSUE TITLE
[Question] Allocate EPTP for each cpu.

### ISSUE THREAD

**Issue by L1B0** [HyperDbg/HyperDbg#153]
Hi, I'm reading the source code of HyperDbg and other hypervisor such as ksm.
I found there is a global variable to store EPT state for all cpu in HyperDbg as well as allocating a EPT to each CPU in ksm. 
I don't understand the difference between those two ways very well because I'm fresh to learn hypervisor. 
Can you explain it? just for the design of HyperDbg is OK.

Thanks a lot!

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for asking.

You can have two approaches to designing an EPT hypervisor. You can use multiple EPTPs (each core has its own EPTP) and one EPT for all the cores. 

The second approach is easier to implement and maintain as you don't have to invalidate and update all cores EPT Table. However, that's one of the biggest mistakes we made in designing HyperDbg. 

Having EPTP for each core gives great flexibility to the hypervisor. It's definitely preferred in a professional hypervisor simply because you can manage each core independently without affecting other cores.

We have this plan to migrate to multiple EPTPs in the future. However, it needs lots of modifications in HyperDbg; that's why we leave it to the future versions.

**Comment by L1B0** [comment]
Thanks for your detailed reply, I have understand the differences better:-)
