### ISSUE TITLE
Maximum Number of breakpoints 

### ISSUE THREAD

**Issue by 0xSensei** [HyperDbg/HyperDbg#181]
https://github.com/HyperDbg/HyperDbg/blob/01d45f4bd0e579188217c0e544cf314b0131b132/hyperdbg/hprdbghv/header/vmm/ept/Ept.h#L18

i want to change the number of breakpoint that get placed in a single page into more than 100+, is it possible with the `epthook` command ?

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for using HyperDbg.
Yeah, that's possible, you can change that value and compile HyperDbg. That should be fine.

**Comment by 0xSensei** [comment]
Thank you for the quick reply, one more question. what i want to do is basically added around 1000+ ept hook on an executable image and do some analysis using `code` tag with a shellcode and a non paged memory. 
The problem im facing is that sometimes i get invalid address error when i try to do `epthook` command and some addresses works fine. i cant show output of it now unfortunately :(, and the vm hangs when i place the breakpoint, is that a side effect of having too many epthook and a lot of vm exit. i have one cpu running on the machine.

Thank you for the amazing project

**Comment by SinaKarvandi** [comment]
Hi again,
Honestly, I don't have any idea, I never test it with 1000+ hooks but that might be a reason. If you have any simplified example scenario where you create this amount of hook, I can test it.

And also, why don't you use `script` tag. We put thousands of hours on it to get rid of creating assemblies. The script engine is well-tested, fast, and also manages every VMX considerations. For example, it guarantees to read memory buffers in a safe-state. Why don't you use it? 

I ask it because we want to get feedback to add support to possible scenarios that are not supported by script engine yet.

Thanks,

**Comment by SinaKarvandi** [comment]
Please don't hesitate to re-open this issue if you feel the problem is not solved yet.
Thanks
