### ISSUE TITLE
cann not connect vmware

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/HyperDbg#186]
sorry my bad english,so see this gif please.
![screenshots](https://user-images.githubusercontent.com/19886504/176926193-508c6c07-43bc-4a6a-b89d-b92abecb8943.gif)

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue.

No, you're just doing the wrong steps, please follow the instructions as described below:

https://docs.hyperdbg.org/getting-started/attach-to-hyperdbg/debug

The method that you used is for connecting windbg to the serial port, not HyperDbg!
You have to run a single command (in hyperdbg-cli) on debuggee to connect to the debugger, it's not like Windbg.

**Comment by SinaKarvandi** [comment]
Please let me know if you still don't understand how to connect to HyperDbg using the steps mentioned above in the link. I can give you more hints to make it work.

**Comment by ddkwork** [comment]
> Please let me know if you still don't understand how to connect to HyperDbg using the steps mentioned above in the link. I can give you more hints to make it work.

Sorry, i am not unstand this. The ept hook syscall can not be on vmi mode?

**Comment by SinaKarvandi** [comment]
> Sorry, i am not unstand this. 
I mean after configuring the host (which you did it correctly), you need to configure the guest (VMware). You don't need to config "msconfig" it's wrong, because "msconfig" is for configuring windbg, not HyperDbg!

In the guest (VMware) run the following command (change the parameters if needed):
`HyperDbg> .debug prepare serial 115200 com2`

And after that, HyperDbg (from guest) connects to the host HyperDbg.

So, let's review the process one more time. First, you need to configure the host (which you did it correctly). Second, you should run the above command in the guest HyperDbg.

> The ept hook syscall can not be on vmi mode?
It works on both VMI mode and Debugger Mode. If you want to use the "!syscall" command, make sure to turn off the PatchGuard because this command is PatchGuard incompatible.
https://docs.hyperdbg.org/commands/extension-commands/syscall#remarks

> what should i do in hyperdbg use ept hook
Yes, you should use EPT Hook. It's pretty easy to do these things by using the script engine.

Please take a look at these examples to make a HyperDbg script for your scenario.

https://docs.hyperdbg.org/commands/scripting-language/examples/conditional-breakpoints-and-events
https://docs.hyperdbg.org/commands/scripting-language/examples/patch-the-normal-sequence-of-execution
https://docs.hyperdbg.org/commands/scripting-language/examples/trace-function-calls
https://docs.hyperdbg.org/commands/scripting-language/examples/access-to-a-shared-variable-from-different-cores

**Comment by SinaKarvandi** [comment]
Please tell me if you still have problems with connecting to HyperDbg or with writing the script.

**Comment by ddkwork** [comment]
> 如果您在连接到 HyperDbg 或编写脚本时仍有问题，请告诉我。



> Please tell me if you still have problems with connecting to HyperDbg or with writing the script.



> Please tell me if you still have problems with connecting to HyperDbg or with writing the script.

pipe server(vmware):
 .debug prepare serial 115200 com1


pipe client(win11):
 .debug remote serial 115200 com1
 
 err, port can't be opened ？
 
.debug remote namedpipe \\.\pipe\HyperDbgPipe


why the picture is \\.\pipe\HyperDebug

![screenshots](https://user-images.githubusercontent.com/19886504/176998898-f6f1a4f7-b834-4619-94e5-c072eb4ac7ee.gif)

**Comment by SinaKarvandi** [comment]
Your order of execution is wrong.
**First**, you have to run HyperDbg on the **host**. **Second**, you need to run HyperDbg on the **guest**.

Execute this command on your **host** first: 
`HyperDbg> .debug remote namedpipe \\.\pipe\HyperDbgPipe
`
**After that**, execute the following command in guest :
`HyperDbg> .debug prepare serial 115200 com2
`
If it didn't work, then use another com port in the guest. (Don't change anything in the host).
For example use com1 instead: 
`HyperDbg> .debug prepare serial 115200 com1
`

**Comment by SinaKarvandi** [comment]
Also, it would be better to use the "master" branch. Not the "dev" branch because it's not well-tested yet.
Please tell me if your problem is fixed or not?

**Comment by ddkwork** [comment]
> Also, it would be better to use the "master" branch. Not the "dev" branch because it's not well-tested yet. Please tell me if your problem is fixed or not?

!epthook nt!NtOpenFile script {
	printf("%ws\n", dq(poi(r8 + 10) + 0x8));
}
0: kHyperDbg> !epthook nt!NtOpenFile script {printf("%ws\n", dq(poi(r8 + 10) + 0x8));}
err, couldn't resolve error at 'nt!NtOpenFile'

 i need install symbol?

**Comment by SinaKarvandi** [comment]
Thanks for using HyperDbg, looking forward to see your feedback about HyperDbg.

> I have a idea: we should filter process name with loop not pid, because has some case we lost the best hook time, if wait we check out the pid, some info was readed, and they can't read agin, like hijack.

Yep, that's easily possible. Also, another option would be to start the process in halt mode and then set the hook (by its PID), and then continue the process. All of them are possible.

By the way, I'm just a simple developer and not a teacher by any means.

**Comment by ddkwork** [comment]
> Thanks for using HyperDbg, looking forward to see your feedback about HyperDbg.
> 
> > I have a idea: we should filter process name with loop not pid, because has some case we lost the best hook time, if wait we check out the pid, some info was readed, and they can't read agin, like hijack.
> 
> Yep, that's easily possible. Also, another option would be to start the process in halt mode and then set the hook (by its PID), and then continue the process. All of them are possible.
> 
> By the way, I'm just a simple developer and not a teacher by any means.

halt mode? not in doc so.

!epthook2 nt!NtDeviceIoControlFile script {printf("IoControlCode %x\n", @rsp+40);}

----------> hello agin,how to get :[rsp+40]？ the @rsp+40 in script was bsod
mov     dword ptr [rsp+40], 10000h      ; IoControlCode   


and     [rsp+72], ebx                   ; OutputBufferLength
and     [rsp+64], rbx                   ; OutputBuffer
mov     dword ptr [rsp+56], 8           ; InputBufferLength
lea     rax, [rsp+152]
mov     [rsp+48], rax                   ; InputBuffer
mov     dword ptr [rsp+40], 10000h      ; IoControlCode   
lea     rax, [rsp+78h+var_18]
mov     [rsp+32], rax                   ; IoStatusBlock
xor     r9d, r9d                        ; ApcContext
xor     r8d, r8d                        ; ApcRoutine
xor     edx, edx                        ; Event
mov     rcx, [rsp+144]                  ; FileHandle
call    cs:__imp_NtDeviceIoControlFile
test    eax, eax

**Comment by ddkwork** [comment]
hello again, i have some question:
1 cpuid changed all eax case, i only want change case as eax==1 not  eax==0 .
2 format %llx look like err :0x3DBAE3BF,see consle output.
3 please support format indent with left and right,like "%016x","%016X","%-016x" etc.
 
					!cpuid pid a58  script {
					printf("rax,rbx,rcx,rdx: %llx\t%llx\t%llx\t%llx\t\n", @rax,@rbx,@rcx,@rdx);
					@rax=0x000306A9;
					@rcx=0x3DBAE3BF;
					@rdx=0xBFEBFBFF;
					}
![screenshots](https://user-images.githubusercontent.com/19886504/178076877-13f25c70-00aa-45ba-a22e-3ab880a935cf.gif)

**Comment by ddkwork** [comment]
> Thanks for using HyperDbg, looking forward to see your feedback about HyperDbg.
> 
> > I have a idea: we should filter process name with loop not pid, because has some case we lost the best hook time, if wait we check out the pid, some info was readed, and they can't read agin, like hijack.
> 
> Yep, that's easily possible. Also, another option would be to start the process in halt mode and then set the hook (by its PID), and then continue the process. All of them are possible.
> 
> By the way, I'm just a simple developer and not a teacher by any means.

hello again, i have some question:
1 cpuid changed all eax case, i only want change case as eax==1 not  eax==0 .
2 format %llx look like err :0x3DBAE3BF,see consle output.
3 please support format indent with left and right,like "%016x","%016X","%-016x" etc.
 
					!cpuid pid a58  script {
					printf("rax,rbx,rcx,rdx: %llx\t%llx\t%llx\t%llx\t\n", @rax,@rbx,@rcx,@rdx);
					@rax=0x000306A9;
					@rcx=0x3DBAE3BF;
					@rdx=0xBFEBFBFF;
					}
![screenshots](https://user-images.githubusercontent.com/19886504/178076937-9da1a5ed-9b5e-43cc-961c-cfd967b1971e.gif)

**Comment by SinaKarvandi** [comment]
Hi, 
Thanks for your feedback.

> 1 cpuid changed all eax case, i only want change case as eax==1 not eax==0 .

What do you mean, if you execute something like this, you'll only edit registers when eax == 0.

```
!cpuid pid a58 script {
     if (eax == 0) {
           //
           // edit registers here
           //
           }
}
```
Do you mean that it's not working?

> 2 format %llx look like err :0x3DBAE3BF,see consle output.
I didn't get the error. What's wrong with it?

> 3 please support format indent with left and right,like "%016x","%016X","%-016x" etc.

It's not that much easy. We implement the "printf" from scratch as the printf for HyperDbg should be vmx-root compatible.
By the way, I'll add it to the future versions' to-do list.

> 4 how to " if $pname == "xxoo.exe" " in script, it tell me the sytax error.
Currently, HyperDbg doesn't support string comparison. Again, it needs script engine modifications, but it's already on the list of to-dos. For now, you can compare each byte of the process id as a character. For example, if you want to check for a process name which is "ABCDE", then you can do something like :

```
if ( db($pname) == 41 && db($pname+1) == 42 && db($pname+2) == 43 && db($pname+3) == 44) {
//
// Do sth
//
}
```

> 5 please support the script api as "strlen","strcpy" for expand "eb” command.

HyperDbg supports `strlen`, and `strcpy` is on the to-do list.

For strlen documentation, please take a look at:
https://docs.hyperdbg.org/commands/scripting-language/functions/strings/strlen

> 6 please support the pid as interger fomat not hex only.

This is something that breaks the semantics of the debugger. All of the values in HyperDbg are supposed to be in hex format. Converting it to an integer format will cause lots of confusion. But I think about adding a to-do so you can use 0n123, adding the '0n' prefix so you can use decimal instead of process id.

> 7 support creat function define struct for filter, for example the nsi net hook needed.
It's again on the to-do list for future versions.


Thanks for your valuable comments, we'll use them to improve HyperDbg. :)

**Comment by ddkwork** [comment]
> 

hi, my means is how to get Context   RegistersState->rax in script?

HvHandleCpuid(PGUEST_REGS RegistersState) {
...
    Context = RegistersState->rax;

if (Context ==1){
reset cpuid.
}

**Comment by SinaKarvandi** [comment]
Hi again,

> hi, my means is how to get Context RegistersState->rax in script?

Yes, now I understand what you mean. You should use the `$context` pseudo-register.

So, basically, you need something like this: 
```
     	!cpuid script {

     	  if ($context == 1) {
     	    @rax = 0x000306A9;
     	    @rcx = 0x3DBAE3BF;
     	    @rdx = 0xBFEBFBFF;
     	  }
     	}
```

**Comment by SinaKarvandi** [comment]
Also, did you solve the problem of comparing the process name (`$pname`)?

**Comment by ddkwork** [comment]
> Also, did you solve the problem of comparing the process name (`$pname`)?

 no, nothing output.
![screenshots](https://user-images.githubusercontent.com/19886504/178159346-663ff93a-4ab6-43a2-aac2-e997ecce2d85.gif)

**Comment by SinaKarvandi** [comment]
> no, nothing output:
Well, is it solved now?

If it's not solved, I made a sample script to test.
```
? {
	printf("process name: %s\n", $pname);
	
	printf("character 1 : %c (%x)\n", db($pname),  db($pname));
	printf("character 2 : %c (%x)\n", db($pname + 1), db($pname + 1));
	printf("character 3 : %c (%x)\n", db($pname + 2), db($pname + 2));
	printf("character 4 : %c (%x)\n", db($pname + 3), db($pname + 3));
	printf("character 5 : %c (%x)\n", db($pname + 4), db($pname + 4));
	
	if (db($pname) == 68 && db($pname + 1) == 79 && db($pname + 2) == 70 && db($pname + 3) == 65 && db($pname + 4) == 72) {
	
		printf("\nProcess name starts with: %c%c%c%c%c\n", 
				db($pname),
				db($pname + 1), 
				db($pname + 2),
				db($pname + 3),
				db($pname + 4));
	}
}
```

> Can you add memcpy and hexdump API?

Yes, it's possible, I'll add memcpy to the next version. Also, would you please provide an example of hexdump API? I don't understand what you exactly mean by hexdump API.

> next version if add decode the function args in stack will be cool.

I think it's not possible because x64 fastcall passes arguments like: rcx, rdx, r8, and r9, and most of the time stack is not used but if you have an example of a working code that decodes x64 fastcall stack, I will try to add it to the HyperDbg.

**Comment by SinaKarvandi** [comment]
> 6 please support the PID as interger fomat not hex only.

I added the support to PID as the decimal in the following commit: https://github.com/HyperDbg/HyperDbg/commit/a0727500fd81ab5ae8c728d5bcc63b2c57f5dd63

Now, if you want to use pid in the decimal format, you can add the '0n' prefix to the number, for example:

`!syscall pid 0n12340`

**Comment by ddkwork** [comment]
> > 6 please support the PID as interger fomat not hex only.
> 
> I added the support to PID as the decimal in the following commit: [a072750](https://github.com/HyperDbg/HyperDbg/commit/a0727500fd81ab5ae8c728d5bcc63b2c57f5dd63)
> 
> Now, if you want to use pid in the decimal format, you can add the '0n' prefix to the number, for example:
> 
> `!syscall pid 0n12340`

sorry my replay so slowly. i am develping a user interface for your hyperdbg and meet some problems with table widget, the ui is not usefully state now . today i will come on to test pname problem.

![image](https://user-images.githubusercontent.com/19886504/178849656-e1fdb893-5ad8-4d15-b2a2-3a7b2aa93ada.png)

**Comment by SinaKarvandi** [comment]
Oh my God, this is a really beautiful UI. Please keep up the great work, and if you're interested, you can host your UI in the HyperDbg organization on GitHub.

**Comment by ddkwork** [comment]
> Oh my God, this is a really beautiful UI. Please keep up the great work, and if you're interested, you can host your UI in the HyperDbg organization on GitHub.

sure, how to join?

**Comment by SinaKarvandi** [comment]
The invitation is sent to you. Please check your email and accept joining HyperDbg's organization on GitHub.
Please host your great project in this repo: https://github.com/HyperDbg/gui

Also, we use Telegram for our coordination. If you have a Telegram account, please send me your username or join HyperDbg's Discussion Group: https://t.me/HyperDbg for more coordination. If you don't use Telegram, no problem, we can coordinate in the discussion section of GitHub.

**Comment by ddkwork** [comment]
> The invitation is sent to you. Please check your email and accept joining HyperDbg's organization on GitHub. Please host your great project in this repo: https://github.com/HyperDbg/gui
> 
> Also, we use Telegram for our coordination. If you have a Telegram account, please send me your username or join HyperDbg's Discussion Group: https://t.me/HyperDbg for more coordination. If you don't use Telegram, no problem, we can coordinate in the discussion section of GitHub.

sorry i can not register Telegram, i am not get the sms code.

**Comment by SinaKarvandi** [comment]
That's okay, I understand. We can use GitHub Discussions instead.

Here's a discussion I just made: 
https://github.com/HyperDbg/HyperDbg/discussions/190

**Comment by SinaKarvandi** [comment]
The `memcpy` function for the script engine is now available.

https://docs.hyperdbg.org/commands/scripting-language/functions/memory/memcpy
