### ISSUE TITLE
the !u command triggers a bsod

### ISSUE THREAD

**Issue by romanholidaypancakes** [HyperDbg/HyperDbg#224]
**Describe the bug**
I don't know if the syntax of this command is correct(I'm trying to use hdbg

**To Reproduce**
under kernel debugging use the following command
```
!u fffff802`7396f010 l 100
```

**Expected behavior**
 the blue screen is not supposed to appear

**Screenshots**

**Desktop (please complete the following information):**
 - Win 10 18363
 - i7-10700F
 - 0.2
 - VMWare Nested Virtualization

**Additional context**
```
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

DRIVER_IRQL_NOT_LESS_OR_EQUAL (d1)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If kernel debugger is available get stack backtrace.
Arguments:
Arg1: ffffaf80f0bf1010, memory referenced
Arg2: 00000000000000ff, IRQL
Arg3: 0000000000000000, value 0 = read operation, 1 = write operation
Arg4: fffff80265c049d2, address which referenced memory

```

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating the issue in HyperDbg.
The problem here is that you specified a virtual address while calling the '!u' which is the disassembler for physical memory. Commands like !u, !u2, !dc, !db, !eq, !eb, etc. that start with '!' operate on physical memory while the equivalent commands for virtual memory is u, dc, db, eb, eq, etc.

So in short, use it like :

```
u fffff802`7396f010 l 100
```
and it should be fine.

Why we didn't check for the address validity to prevent BSOD? I've mentioned in the source code, I don't know a way of checking the validity of physical address. We perform the checks for virtual address but I couldn't find a way to check for physical address. So, if you knew how to check for it, let me know, so we can implement a physical memory validity check in such cases, otherwise, you can simply ignore this issue and use the virtual address variants of these commands (u, u2, db, dc, eb, etc.).

**Comment by SinaKarvandi** [comment]
HyperDbg now checks for the validity of physical addresses (as the latest commit in the 'dev' branch').

**Comment by SinaKarvandi** [comment]
https://github.com/HyperDbg/HyperDbg/commit/40c9f5ac6e4ed803290c374c12ce5b4e0967938e
