### ISSUE TITLE
EPT violation error when i try to clear a !monitor event

### ISSUE THREAD

**Issue by begnoob123** [HyperDbg/HyperDbg#231]
I encounter an EPT violation error when I try to clear a !monitor event. Debuggee VM BSODs with KERNEL_SECURITY_CHECK FAILURE and HyperDbg on Debugger VM hangs i.e. does not accept any input. 

I want to debug a driver. The driver will use ExAllocatePoolWithTag to allocate new pool memory and do some read/writes to the pool memory. The driver will then free the pool memory at the end of the IOCTL request. I want to use HyperDbg to monitor the newly allocated pool memory for any read/writes. 
My steps are:
1. Set a breakpoint on the ExAllocatePoolWithTag instruction in the driver.
2. When breakpoint is hit, get the return value from the ExAllocatePoolWithTag function. The return value is the address of memory that I want to monitor.
3. Set the command: !monitor rw [start_addr] [end_addr] pid 1234
4. Let the debuggee run to get the !monitor results.

**1st Problem - No output**
However, HyperDbg does not return any result. I have read in the HyperDbg documentation that events like !monitor actually continues the debuggee for some time before halting again. Might this be the reason why I do not get any outputs? (It is confirmed that there will be read/writes to the newly allocated pool.) In the HyperDbg documentation, I saw that there is a workaround for syscall events where we can set the syscall event before debugging the process. But in my case, I cannot set the event before as I need the return address from the ExAllocatePoolWithTag function. Are there any workarounds for my case or does HyperDbg not support this types of scenarios?

**2nd Problem - BSOD**
Another problem is that the Debugge VM BSODs and HyperDbg returns with an EPT violation error. 

EPT violation @ fffff8013476ae15
![image](https://github.com/HyperDbg/HyperDbg/assets/119290010/0178152b-9db7-4d0e-80fd-4faca49abfe5)

I think this might be a problem with the driver freeing the pool memory with ExFreePoolWithTag at the end of the IOCTL request. I attached WinDbg to the debuggee and tried to see what instruction was at fffff8013476ae15. The instruction is in the hprdbghv!PoolManagerFreePool function: cmp [rax], rcx. 

Instructions @ address fffff8013476ae15
![image](https://github.com/HyperDbg/HyperDbg/assets/119290010/7ed6e14e-5059-4af7-83a5-ef2a65d96fb8)

I found out that the rax register actually contains the value 0 which might be the reason why the debuggee BSODs as it is trying to access invalid address 0x0. HyperDbg  returns an EPT violation also because it is trying to access an invalid address? I am not sure if I am understanding this correctly and would appreciate your feedback on this. 
Does this mean that every time I want to monitor a range of memory that might get freed, I need to clear the event before it is freed? 

Setup:
1. Debuggee VMware VM (Windows10 22H2 19045)
2. Debugger VMware VM (Windows10 22H2 19045)

Thank you.

**Comment by SinaKarvandi** [comment]
Hi,
Thanks a lot for reporting these issues and providing us with your feedback.

> 1st Problem - No output
> However, HyperDbg does not return any result. I have read in the HyperDbg documentation that events like !monitor actually continues the debuggee for some time before halting again. Might this be the reason why I do not get any outputs? (It is confirmed that there will be read/writes to the newly allocated pool.) In the HyperDbg documentation, I saw that there is a workaround for syscall events where we can set the syscall event before debugging the process. But in my case, I cannot set the event before as I need the return address from the ExAllocatePoolWithTag function. Are there any workarounds for my case or does HyperDbg not support this types of scenarios?

You're right. HyperDbg won't support this scenario as it runs the VM for some time and returns back to the debugger, so you might lose the context. At first, when I started developing HyperDbg, I didn't have any solution to this problem. Because in VMX-root mode RFLAGS.IF flag is disabled and we cannot use IPI (or DPC) to interrupt other cores to invalidate their EPT TLB cache, so we need to run the guest in VMX non-root mode for some time and interrupt the guest again to notify all the cores about cache invalidation. But right now, I know a way to avoid this to apply event commands, in real-time but this needs some design reconsideration to be implemented. I try to re-design these parts so we can support these scenarios but it needs some time and tests as it's not really a trivial fix. I hope I can fix it probably in the coming months.

For now, I suggest a quick and dirty solution. You can allocate some pools (manually) using your own driver. Put some !monitor commands on the allocated address. After that, when your target driver wants to allocate some pools, ignore the allocation (return the address of the previously allocated pool in 'RAX') and it should be fine.


> 2nd Problem - BSOD

About problem 2, I can confirm that I see this behavior sometimes but honestly, I was not successful in reproducing this error. For me, it works fine right now. Can you please provide the commands that you use to reproduce the error, so I can fix it?

**Comment by SinaKarvandi** [comment]
As it was a critical bug, I also tagged the fixed version and released a new version with the patch (v0.2.1).
Please consider re-opening the issue and informing me if the bug is still not fixed.

Thanks for reporting it!
