### ISSUE TITLE
Is it possible to extend hyperdbg to support AMD CPU?

### ISSUE THREAD

**Issue by louwangzhiyuY** [HyperDbg/HyperDbg#259]
as you know,  AMD processor perfermance is very stong and have a large market share.  it will be better if hyperdbg can run on AMD platform.

**Comment by SinaKarvandi** [comment]
Hi,
Yes, AMD processors are strong, no doubt. However, adding support for AMD processors is not a simple task. It's part of our long-term plan, but we currently have many unfinished tasks related to Intel processors. Additionally, we're prioritizing porting HyperDbg to Linux. Due to limited developer resources and time, we can't support AMD processors at the moment. We hope that members of the community can join us and help speed up the process of adding AMD processor support.
