### ISSUE TITLE
Failed to install or load the driver

### ISSUE THREAD

**Issue by Chrys4lisfag** [HyperDbg/HyperDbg#27]
I am getting Failed to install or load the driver when  .debug prepare serial or .debug local(load vmm)
tested on 1909 and 2004
tested on local and vmware

Is this supposed to work? or cuz it hasn`t been released yet?

**Comment by SinaKarvandi** [comment]
Hello,
No there is a problem here, are you sure that you build driver ? there should be a file named hprdbghv.sys
Is it in the build directory?

**Comment by Chrys4lisfag** [comment]
There is: https://i.imgur.com/ftDUaW9.png

**Comment by SinaKarvandi** [comment]
Would you pls send a picture of the commands you used and the error code?

**Comment by Chrys4lisfag** [comment]
https://i.imgur.com/9yo8ZB9.png

**Comment by SinaKarvandi** [comment]
HyperDbg is successfully loaded on your machine!

The problem is that you used the remote debugger mode of HyperDbg. It means that there should be a host which listens on a COM port or a named pipe then you should use '.debug prepare xxx' in your guest.

If you want to use HyperDbg locally (vmi-mode), there is no need to execute the '.debug' command, it's just for remote debugging. You have two options, first, you can execute '.connect local' then 'load vmm' to use HyperDbg in vmi-mode. second, create a named pipe as described here :
https://docs.hyperdbg.com/getting-started/attach-to-hyperdbg/debug
and use .debug command.

Please take a look at these articles:
https://docs.hyperdbg.com/getting-started/attach-to-hyperdbg

**Comment by Chrys4lisfag** [comment]
The screenshot is from guest. This was on host that time: https://i.imgur.com/Oze3Mf3.png

If I use ,connect local + load vmm there is load driver error as well:  https://i.imgur.com/O6nUTDu.png

**Comment by SinaKarvandi** [comment]
When you see those messages below, it means that HyperDbg is loaded successfully.
However, there seems to be a problem as the error message should not be shown.
The error message is shown as the result of the following function :
`BOOLEAN CommandLoadVmmModule();`

Please investigate when the above function decides to return FALSE. This way, we can understand the root cause of this bug.

**Comment by Chrys4lisfag** [comment]
I am also getting these system crashes: https://i.imgur.com/hSFHxHi.png https://i.imgur.com/yTy7ksp.png
Will test thing today. Can you tell me what win ver\build is 100% compatible and tested with this hv?

**Comment by SinaKarvandi** [comment]
Well, we're using 20H2, but the errors you sent are weird. Also, please use Debug "not release" version of HyperDbg and tell us if the problem with crashing processes is solved or not.

**Comment by Chrys4lisfag** [comment]
Error for Release build
```
if (!CommandLoadVmmModule()) {
      ShowMessages("Failed to install or load the driver\n");
      return;
    }

```
Error for Debug build
```
 if (!CommandLoadVmmModule()) {
      ShowMessages("Failed to install or load the driver #1\n");
      return FALSE;
    }
```

So that was the cause. System Processes are not crashing as well. (might be cuz I had 2 number of cores in VM or smth with my windows image). Now everything is fine.

I am trying !syscall feature and want to ask about sysID and PID format. Does it matter to have 0x for the pid and syscall id hex values or not? I am getting BSODed after !syscall when I continue to debugger (CRITICAL PROCESS DIED)

**Comment by Chrys4lisfag** [comment]
Hm. there still errors with taskmgr and process hacker when I open them after hv load: https://i.imgur.com/H4o660c.png https://i.imgur.com/d5nZSYR.png

**Comment by SinaKarvandi** [comment]
> Hm. there still errors with taskmgr and process hacker when I open them after hv load: https://i.imgur.com/H4o660c.png https://i.imgur.com/d5nZSYR.png

These errors are really hard to investigate. If you find the problem, please let us know. actually, we're not tested HyperDbg, but it takes time to solve all of these problems.
