### ISSUE TITLE
The result of executing ". process pid xxx" is always unstable

### ISSUE THREAD

**Issue by zero-168** [HyperDbg/HyperDbg#331]
**Describe the bug**
In Debugger mode, it is difficult to break. This is evident in the prolonged lack of response after executing .process pid xxx. After repeatedly using CTRL+C and then executing .process pid xxx again, it occasionally breaks (always at the kernel layer address).

**To Reproduce**
The program code for testing is as follows :

#include <iostream>
#include<Windows.h>
int main()
{
    while (true)
    {
        std::cout << "Hello World!\n";
        Sleep(2000);
    }
}

If I change Sleep(2000) to Sleep(10), the likelihood of success for the .process pid xxx command will significantly increase.

**Comment by zero-168** [comment]
Sometimes it takes more than 10 minutes without success, but sometimes it interrupts immediately. Is it possible that the interception occurs only after the target program has executed certain kernel operations by the operating system?
Test environment:
win10 19045
CPU: E5 2696 V3

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for reporting this issue. Actually, this is an expected behavior and it's because of the design of the '.process' command which relies on clock-interrupts. Remember, the first principle of designing HyperDbg is to be as OS-independent as possible. Because of that, whenever a clock-interrupt happens in your process, we'll intercept it (this approach relies on VT-x facilities to intercept processes, rather than OS codes).

In the above case, `Sleep(10)` will likely be triggered immediately and HyperDbg had the chance to intercept the context of the process. Still, when you use `Sleep(2000)`, for sure the quantum cycle of Windows for switching between different processes is less than 2 seconds, so before any context-switch (by the clock-interrupt) happens, the application tries to notify the Operating System that it's now in an idle state. It needs to be context-switched manually as it no longer needs to be executed (at least for 2 seconds). As the process is switched manually (e.g., by using SYSCALL using WaitForSingleObject), the next time that the clock-interrupt triggers, the process is changed and HyperDbg cannot intercept it as the system is now in an entirely different process.

How to fix it? You have several options in HyperDbg that might be effective. First, you can use the '[.process2](https://docs.hyperdbg.org/commands/meta-commands/.process)' command. You can also use '[.thread or .thread2](https://docs.hyperdbg.org/commands/meta-commands/.thread)' commands.

The differences between the design of these two commands and the situations where each command should be used is described here:
https://docs.hyperdbg.org/tips-and-tricks/considerations/difference-between-process-and-thread-switching-commands

Please make sure to read it.

If none of the above methods was not effective, you can use the '[!monitor](https://docs.hyperdbg.org/commands/extension-commands/monitor)' command's execution trap. First, you need to know the address of the main module of your process (by using the '[lm](https://docs.hyperdbg.org/commands/debugging-commands/lm)' command). Once you know the address of the main module, the next step is to set an [execution monitor](https://docs.hyperdbg.org/commands/extension-commands/monitor) on the target address of the main module. This way, once any code in the main module is tried to be executed, HyperDbg will break and notify you.

I hope it helps, let me know if you have any questions.

**Comment by zero-168** [comment]
Ok,Thanks!
