### ISSUE TITLE
v0.8.2 Flagged by Antivirus

### ISSUE THREAD

**Issue by themooer1** [HyperDbg/HyperDbg#358]
**Describe the bug**
HyperDbg v0.8.2 has started being flagged by antivirus software. v.0.8.1 is not being flagged except generically by three minor antivirus providers and Google.

**To Reproduce**
1. Download v0.8.2 [https://github.com/HyperDbg/HyperDbg/releases/download/v0.8.2/hyperdbg-v0.8.2.zip](https://github.com/HyperDbg/HyperDbg/releases/download/v0.8.2/hyperdbg-v0.8.2.zip)
2. Upload to virustotal

**Screenshots**
<img width="1434" alt="Screenshot 2024-05-03 at 12 02 53 AM" src="https://github.com/HyperDbg/HyperDbg/assets/8960671/95b67f01-716f-4447-b329-0df0716f57c8">

**Comment by SinaKarvandi** [comment]
That's kind of weird, from v0.8.1 to v0.8.2 we're not doing anything special other than refactoring. It's either a false positive or something wrong happened here. We're not building HyperDbg on our own system, everything is built in [github-actions](https://github.com/features/actions) so I'm gonna investigate it now.

**Comment by SinaKarvandi** [comment]
Going through all the [modifications ](https://github.com/HyperDbg/HyperDbg/commit/103874d777d681324ac61948c8eae06a237ae812)made from v0.8.1 to v0.8.2, I couldn't find any evidence of a suspicious activity into the source code. So, I assume that this is false positive made by AVs. Though I continue the investigation. Pls let me know if you find anything new related to this issue.

**Comment by SinaKarvandi** [comment]
My very first investigation results indicate that the problem is mainly with the way that we compile 'hyperdbg-cli.exe' since I compiled the release version of hyperdbg-cli.exe again on my PC and it shows the same result in VT. I did a 'debug' version compilation and it didn't indicate the same problem. I'm gonna find the exact flag that causes this problem now.
![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/1c7aaa56-5fc5-4cf4-a634-d56d62e87629)

**Comment by SinaKarvandi** [comment]
The problem is now solved at v0.8.3. I changed the release flag of `hyperdbg-cli` to `Multi-threaded Debug (/MTd)` and it seems to fix the problem.

https://www.virustotal.com/gui/file/26304077a9822ba8eb28b0c50c2e5cb2e7dd392fec7d27323ca902bf18fa070b?nocache=1

![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/61571b02-1a84-4c53-95b8-dcb846456011)

**Comment by SinaKarvandi** [comment]
I've checked it again and the problem seems to be solved. Please reopen the issue if the problem still exists.

**Comment by themooer1** [comment]
Thanks!
