### ISSUE TITLE
I think hidden hook may crash some situations

### ISSUE THREAD

**Issue by prnuimeer** [HyperDbg/HyperDbg#400]
Hello, I have a question. 
How did you solve the problem of referencing the function from another thread while performing a hidden hook? 
I think this problem is related to scheduling not multi-core.
To simplify this problem, let's consider only one core, below.  
A thread A excuted only 4 bytes of the prologue of function, after that context switching occured. Afterwards, thread B performs a hidden hook and flushes tlb. (Assume the patching jump code is 5 bytes) The thread A executes and tries to read the next 4-byte code previously executed, but this command's prefix is a last 1byte of 5-byte instruction patch. This causes unintended code and causes thread B to crash.
How do you think about this problem?

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue. 
I think this problem only happens for the '[!epthook2](https://docs.hyperdbg.org/commands/extension-commands/epthook2)' command, not the main EPT hook ('[!epthook](https://docs.hyperdbg.org/commands/extension-commands/epthook)'). The main EPT hook only patches one byte and puts a breakpoint (0xcc) and since one byte is the shortest granularity this condition never happens. 

For the '!epthook2' issue, I believe it is a race condition that is highly unlikely to occur. The chances of this event happening are extremely low.
