### ISSUE TITLE
Please make possible to cancel script execution by ctrl+c or smth

### ISSUE THREAD

**Issue by kqikz** [HyperDbg/HyperDbg#413]
!monitor x 8f7150 l 3  script {
	for (i = 0; i < len; i = i - 4){
		printf("%x",i);
	}
}

endless loop can not be stopped by ctrl+c

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue. Actually, this one is not possible since in HyperDbg scripts of events or the '?' evaluation command are all evaluated in the kernel (VMX-root mode) and it's not possible to interrupt them like user-mode codes. So, this one is almost impossible based on the current design.

**Comment by kqikz** [comment]
Hm, but is it possible to initiate .debug close, for example?

**Comment by SinaKarvandi** [comment]
What do you mean? `.debug close` after running `!monitor`? 🤨

**Comment by kqikz** [comment]
when some script is hanged up and ctrl+c(or better other combination) is pressed, send .debug close. now i cant exit script execution at all, and need to restart vm.

**Comment by SinaKarvandi** [comment]
The thing is, once the VM is stuck in VMX root-mode, there is no way HyperDbg could communicate with that. So, HyperDbg cannot force it to exit or close :(

**Comment by kqikz** [comment]
i see...

**Comment by SinaKarvandi** [comment]
Nope, event injection is for injecting interrupts/exceptions/faults from VMX-root mode (e.g., HyperDbg) to the kernel-mode (e.g., Windows). HyperDbg's script engine evaluator engine runs in VMX root-mode.
