### ISSUE TITLE
Buffer not accessible in script

### ISSUE THREAD

**Issue by kqikz** [HyperDbg/HyperDbg#471]
.start path C:\dbg\getch.exe

g

!monitor x 00007ff730371016 l 8 buffer 10 asm code {mov byte ptr ds:[rcx], 20; ret;} script {
		printf("TRIGGER %x\n",db($buffer));
}

type any letter(except q) and press enter

TRIGGER 0 is always printed
[getch.zip](https://github.com/user-attachments/files/16830581/getch.zip)

**Comment by SinaKarvandi** [comment]
As discussed in the Telegram group. It's better to have another solution like supporting assembly codes in the script instead of modifying the design.

The thing is, actions are independent of each other means that each action has its own custom buffer so both the script and the assembly have different requested buffers.
![image](https://github.com/user-attachments/assets/a3122b91-ae25-4bee-afb1-3096e8a4072b)
