### ISSUE TITLE
Use .pagein will  100% trigger windows blue screen. 

### ISSUE THREAD

**Issue by junetou** [HyperDbg/HyperDbg#488]
**Describe the bug**
I use debugger mode to debug process. And i want to debug dll running condition. i use "!monitor rw 00007ffb6bee0000 l 500" command to monitor memory. but kHyperDbg show error (err, invalid address (c0000005)). then i use ".pagein w 00007ffb6bee0000" command bring the page into the RAM. then i use g command. the guess windows will 100% trigger blue screen.

**To Reproduce**
1. Go to 'host computer run kHyperDbg and run command `!monitor rw 00007ffb6bee0000 l 500`.'
2. The host computer will show 'err, invalid address (c0000005)' error.
3. Go to 'host computer run kHyperDbg and run command `.pagein w 00007ffb6bee0000`.'
4. Go to 'host computer run kHyperDbg and run command `g`.'
5. The guest computer will 100% trigger blue screen.

**Expected behavior**
The kHyperDbg can monitor 00007ffb6bee0000 memory

**Screenshots**
![20241218-110518](https://github.com/user-attachments/assets/12055e8b-5e04-418f-851d-6d8dfbd426c0)

**Desktop (please complete the following information):**
 - OS: [e.g. Win 10 22H2]
 - Processor [e.g. Intel i3-10100]
 - Version [e.g. 0.11.0]
 - Environment [VMWare Workstation Virtualization]

**Additional context**

**Comment by SinaKarvandi** [comment]
Hi,

Thanks for creating this issue. 

There might be two issues in this scenario.
First, the address might be actually invalid. Are you 100% sure that the address is valid?

If the address is invalid in the OS, HyperDbg will just inject a #PF and it will crash the system since Windows assumes it as a not-expected error.

Second, it's kinda weird that you used `.pagein w` which means injecting a 'write'. Change it to the default behavior (without 'w') might fix the issue, so the command should be:
```
.pagein 00007ffb6bee0000
```

Let me know whether the above command fixes the problem or not.

**Comment by junetou** [comment]
no bug.
Link to decrypt question:https://t.me/HyperDbg/8438
