### ISSUE TITLE
Workaround for Log the State

### ISSUE THREAD

**Issue by EquilMinis** [HyperDbg/HyperDbg#7]
While the Log To State features is being worked on, I was wondering if there's currently a way to log the state of the processor when an event is triggered, perhaps custom code could be executed to create the same effect?

Currently I'm trying to find the state of the cpu when certain code writes to a page of memory (using !monitor), is it possible to log this at all with a local debug session?

**Comment by SinaKarvandi** [comment]
Log the state feature is not yet implemented in HyperDbg but you can use this way,

go to the following line and print whatever you want from the states (registers are also available there),

https://github.com/HyperDbg/HyperDbg/blob/de7bb558894d307b3ee64bef02cc4fa30a719831/hyperdbg/hprdbghv/Debugger.c#L803

use !monitor command and will print whatever you want from the kernel.

**Comment by EquilMinis** [comment]
Thanks for the fast reply!

I wanted to make sure I'm using it properly, is this correct?
```
!monitor w DEADB000 DEADBFFF pid 20D0 code { 90 }
```

That should run the `DebuggerPerformRunTheCustomCode` function whenever that virtual page is written to, right? Unfortunately nothing is logged to the console when I write to the page, am I doing something wrong?

**Comment by SinaKarvandi** [comment]
Yw.
By default, HyperDbg accumulates the kernel messages and won't send it to the user-mode immediately, you can see the results immediately if you change this line to TRUE:

https://github.com/HyperDbg/HyperDbg/blob/de7bb558894d307b3ee64bef02cc4fa30a719831/hyperdbg/include/Configuration.h#L53

Your command is ok, but I'm not sure whether it works on user-mode pages or not (it 100% works on kernel) it is because HyperDbg is not yet ready as I wrote in GitHub page, but sure you can use this command in kernel page and maybe in user-mode pages.
