### ISSUE TITLE
entry point exe file

### ISSUE THREAD

**Issue by xSanx** [HyperDbg/HyperDbg#99]
recommend how to start debugging a user's process (.exe) from a  "Entry point" as normal debuggers do ... Maybe somehow cling to it as a child from explorer.exe?

**Comment by SinaKarvandi** [comment]
Let me implement something for it :)
I'll ping you back soon.

**Comment by SinaKarvandi** [comment]
During the past few days, I have been working on this feature. My first attempt was to create a suspended process, read modules base addresses from PEB, and put an EPT Hook (hidden breakpoint on the entry point). I implemented it (https://github.com/HyperDbg/HyperDbg/commit/837fa7698195d1cabb0a7c2606508411a5c11376),(https://github.com/HyperDbg/HyperDbg/commit/efd20084ca3f2251ce1913988a61b5716e0f6c10), and (https://github.com/HyperDbg/HyperDbg/commit/6a5807852b0caa437d3069b669aa1e05838c2f2c) but it didn't work.

The reason was that Windows didn't initialize the PEB LDR modules when a process was opened in a suspended state. This method can't be used.

Now, there is a chance to get the module entry point by monitoring access to PEB LDR of that process.

I'm currently working on it to see if we can use this method to get the entry point of EXE.

**Comment by SinaKarvandi** [comment]
Hey, 

I implemented the very first '.attach' mechanism in HyperDbg.

Please use this commit (https://github.com/HyperDbg/HyperDbg/commit/2d64d2296d5092cb9f4a41f276251bed2363222b) only this commit from the `attaching-mechanism` branch.

You should use a `t` after the debugger is paused on the entry point (the first instruction's disassembling is not correct if the module is not previously loaded, this problem will be solved).
 
This command is not fully implemented, not working on VMI Mode (only in Debugger Mode), the detaching mechanism is not yet implemented and it's not well-tested yet. All in all, it's in the very first stages of implementation but it will satisfy your needs.

Use this command:
`.attach path C:\Users\Sina\Desktop\x32\x32dbg.exe`

I will notify you of the future progress on this command on this issue.
![Capture](https://user-images.githubusercontent.com/13383992/147889389-47e39a9c-766a-4cf7-b06e-380dc6f932c3.PNG)

**Comment by SinaKarvandi** [comment]
okay,
I added a user-mode debugging mechanism based on your needs; please look at the demo.

This user-mode debugger is still at the first step like it still doesn't have the 'p' step-over command or is not synced with other commands. I'll keep updating these functionalities to give you a better user-mode debugging experience. Please test it and tell me your feedback.

https://user-images.githubusercontent.com/13383992/151983131-0a0b1fb9-cee8-4e34-a697-9dafcb2c92db.mp4
